# Generated by Django 4.0.5 on 2022-06-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0002_alter_jogos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='nome_do_jogo',
            field=models.CharField(max_length=30, verbose_name='nome_do_jogo'),
        ),
    ]
