# Generated by Django 4.0.5 on 2022-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_alter_jogos_nome_do_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='nome_do_jogo',
            field=models.CharField(max_length=30),
        ),
    ]
