# Generated by Django 4.0.5 on 2022-06-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_alter_jogos_nome_do_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='descrição_do_jogo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
