# Generated by Django 4.0.5 on 2022-06-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_alter_jogos_descrição_do_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='descrição_do_jogo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='valor_do_jogo',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
