# Generated by Django 4.0.5 on 2022-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0007_alter_jogos_descrição_do_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogos',
            name='tipo_de_jogo',
            field=models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Corrida', 'Corrida'), ('Futebol', 'Futebol'), ('Outros', 'Outros'), ('RPG', 'RPG'), ('Sobrevivencia', 'Sobrevivencia')], max_length=30),
        ),
    ]
